on:
  push:
    branches:
      - staging
      - "b-rust-**"

name: Build for staging env

jobs:
  linux_arm7:
    name: Linux ARMv7
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    # prevent endless github action loop
    if: ${{ github.event.head_commit.committer.name != 'github-actions[bot]' }}
    steps:
      - name: Install gzip
        run: sudo apt-get update && sudo apt-get install -y gzip
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: armv7-unknown-linux-musleabihf
          override: true
      - run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
      - uses: actions-rs/cargo@v1
        with:
          command: binstall
          args: -y cargo-get
      - uses: actions-rs/cargo@v1
        with:
          command: binstall
          args: -y cargo-edit
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: zipsign

      - name: update version in cargo
        run: |
          cargo set-version --bump patch -p test --manifest-path ./practice/rust/test/Cargo.toml
          echo "RUST_VERSION=$(cargo-get --entry ./practice/rust/test/Cargo.toml package.version)" >> $GITHUB_ENV

      - name: capture last changelog change
        run: |
          {
            echo 'RUST_CHANGELOG_DIFF<<EOF'
            git diff HEAD~1 -- CHANGELOG.md
            echo EOF
          } >> "$GITHUB_ENV"

      # commit bump version
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "version update: ${{ env.RUST_VERSION }}"

      - name: get latest commit hash
        run: |
          echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Tag
        id: tag_version_rust
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: staging-${{ env.RUST_VERSION }}
          tag_prefix: rust-
          commit_sha: ${{ env.COMMIT_HASH }}

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --manifest-path ./practice/rust/test/Cargo.toml

      - name: Run UPX
        uses: crazy-max/ghaction-upx@v2
        with:
          version: latest
          files: |
            ./practice/rust/test/target/debug/test
          args: -q --brute

      - name: Create branch to bump main branch
        run: |
          cargo set-version --bump minor -p test --manifest-path ./practice/rust/test/Cargo.toml
          echo "RUST_VERSION=$(cargo-get --entry ./practice/rust/test/Cargo.toml package.version)" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: bump/${{ env.RUST_VERSION }}
          commit-message: Bump version ${{ env.RUST_VERSION }}
